# Auto-generated by grail — do not edit

from typing import Any

node_text_input: str | None
target_file_input: str | None

async def read_file(path: str) -> str:
    """Read the text contents of a file."""
    ...

async def file_exists(path: str) -> bool:
    """Check if a file or directory exists."""
    ...

async def run_command(cmd: str, args: list[str]) -> dict[str, Any]:
    """Run a command in the sandbox."""
    ...

async def run_json_command(cmd: str, args: list[str]) -> Any:
    """Run a command and parse its stdout as JSON."""
    ...
