"""Remora public API surface."""

from remora.core.cairn_bridge import CairnWorkspaceService
from remora.core.cairn_externals import CairnExternals
from remora.core.config import (
    BundleConfig,
    ConfigError,
    DiscoveryConfig,
    ErrorPolicy,
    ExecutionConfig,
    ModelConfig,
    RemoraConfig,
    WorkspaceConfig,
    load_config,
    serialize_config,
)
from remora.core.context import ContextBuilder, RecentAction
from remora.core.discovery import (
    CSTNode,
    LANGUAGE_EXTENSIONS,
    NodeType,
    TreeSitterDiscoverer,
    compute_node_id,
    discover,
)
from remora.core.errors import (
    ConfigError,
    DiscoveryError,
    ExecutionError,
    GraphError,
    RemoraError,
    WorkspaceError,
)
from remora.core.event_bus import EventBus, EventHandler
from remora.core.event_store import EventSourcedBus, EventStore
from remora.core.events import (
    AgentCompleteEvent,
    AgentErrorEvent,
    AgentSkippedEvent,
    AgentStartEvent,
    GraphCompleteEvent,
    GraphErrorEvent,
    GraphStartEvent,
    HumanInputRequestEvent,
    HumanInputResponseEvent,
    KernelEndEvent,
    KernelStartEvent,
    ModelRequestEvent,
    ModelResponseEvent,
    RemoraEvent,
    ToolCallEvent,
    ToolResultEvent,
    TurnCompleteEvent,
)
from remora.core.executor import AgentState, ExecutorState, GraphExecutor, ResultSummary
from remora.core.graph import AgentNode, build_graph, get_execution_batches
from remora.core.tools import RemoraGrailTool, build_virtual_fs, discover_grail_tools
from remora.core.workspace import AgentWorkspace, CairnDataProvider, CairnResultHandler, WorkspaceManager
from remora.utils import PathResolver

__all__ = [
    "ConfigError",
    "DiscoveryError",
    "ExecutionError",
    "GraphError",
    "RemoraError",
    "WorkspaceError",
    "BundleConfig",
    "DiscoveryConfig",
    "ErrorPolicy",
    "ExecutionConfig",
    "ModelConfig",
    "RemoraConfig",
    "WorkspaceConfig",
    "load_config",
    "serialize_config",
    "AgentCompleteEvent",
    "AgentErrorEvent",
    "AgentSkippedEvent",
    "AgentStartEvent",
    "GraphCompleteEvent",
    "GraphErrorEvent",
    "GraphStartEvent",
    "HumanInputRequestEvent",
    "HumanInputResponseEvent",
    "KernelEndEvent",
    "KernelStartEvent",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "RemoraEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "TurnCompleteEvent",
    "EventBus",
    "EventHandler",
    "EventSourcedBus",
    "EventStore",
    "AgentNode",
    "build_graph",
    "get_execution_batches",
    "AgentState",
    "ExecutorState",
    "GraphExecutor",
    "ResultSummary",
    "CSTNode",
    "LANGUAGE_EXTENSIONS",
    "NodeType",
    "TreeSitterDiscoverer",
    "compute_node_id",
    "discover",
    "ContextBuilder",
    "RecentAction",
    "AgentWorkspace",
    "CairnDataProvider",
    "CairnExternals",
    "CairnResultHandler",
    "CairnWorkspaceService",
    "WorkspaceManager",
    "RemoraGrailTool",
    "build_virtual_fs",
    "discover_grail_tools",
    "PathResolver",
]
