# Auto-generated by grail — this is what Monty actually executes

if not isinstance(count, int):
    raise ValueError('count must be int')
result = {'summary': f'count={count}', 'outcome': 'success'}
result