# Auto-generated by grail — this is what Monty actually executes

from typing import Any
try:
    if not source_code:
        raise ValueError('Source code is required.')
    if not issue_code or line_number <= 0:
        error_message = 'issue_code and line_number are required.'
        result = {'result': {'success': False, 'message': error_message}, 'summary': f'Error: {error_message}', 'knowledge_delta': {}, 'outcome': 'error', 'error': error_message}
    else:
        fix_result = await apply_ruff_fix(path=file_path, issue_code=issue_code)
        exit_code = int(fix_result.get('exit_code', 0) or 0)
        stderr = str(fix_result.get('stderr', ''))
        new_content = fix_result.get('content', source_code)
        if exit_code not in {0, 1}:
            error_message = stderr.strip() or f'ruff exit code {exit_code}'
            result = {'result': {'success': False, 'message': error_message}, 'summary': f'Error: {error_message}', 'knowledge_delta': {}, 'outcome': 'error', 'error': error_message}
        else:
            success = new_content != source_code
            if success:
                message = f'Applied fix for {issue_code} at line {line_number}'
                summary = message
                outcome = 'success'
                result = {'result': {'success': True, 'message': message, 'fixed_code': new_content}, 'summary': summary, 'knowledge_delta': {'fix_applied': success, 'last_fix_issue_code': issue_code, 'last_fix_line': line_number}, 'outcome': outcome, 'written_file': file_path, 'content': new_content}
            else:
                message = 'No fixable issue at that location'
                summary = f'No fixable issue for {issue_code} at line {line_number}'
                outcome = 'partial'
                result = {'result': {'success': False, 'message': message}, 'summary': summary, 'knowledge_delta': {'fix_applied': success, 'last_fix_issue_code': issue_code, 'last_fix_line': line_number}, 'outcome': outcome}
except Exception as exc:
    result = {'result': {'success': False, 'message': str(exc)}, 'summary': f'Error: {exc}', 'knowledge_delta': {}, 'outcome': 'error', 'error': str(exc)}
result