# Auto-generated by grail — do not edit

from typing import Any

source_code: str
file_path: str
issue_code: str
line_number: int

async def apply_ruff_fix(path: str, issue_code: str) -> dict[str, Any]:
    """Apply ruff fix for a specific issue code."""
    ...
