# Auto-generated by grail — do not edit

source_code: str
file_path: str
issue_code: str
line_number: int
fixed_content: str | None
exit_code: int
stderr: str

async def write_file(path: str, content: str) -> bool:
    ...
