# Auto-generated by grail — this is what Monty actually executes

async def _read_optional(path: str) -> str | None:
    if await file_exists(path=path):
        return await read_file(path=path)
    return None

async def _resolve_target_file() -> str | None:
    if target_file_input:
        return target_file_input.strip()
    stored = await _read_optional(path='.remora/target_file')
    if stored:
        return stored.strip()
    return None

def _line_count(content: str) -> int:
    if not content:
        return 0
    return len(content.splitlines())
try:
    target_file = await _resolve_target_file()
    if not target_file:
        raise ValueError('Target file not found for linting.')
    content = await read_file(path=target_file)
    result = {'content': content, 'lines': _line_count(content)}
except Exception as exc:
    result = {'error': str(exc)}
result