# Auto-generated by grail — this is what Monty actually executes

try:
    if not path_value:
        raise ValueError('Test file path is required.')
    await write_file(path=path_value, content=content)
    result = {'success': True, 'path': path_value}
except Exception as exc:
    result = {'success': False, 'error': str(exc)}
result