# Auto-generated by grail — this is what Monty actually executes

workspace_value = workspace_id or 'unknown'
try:
    status = 'success' if tests_passing >= tests_generated else 'failed'
    result = {'status': status, 'workspace_id': workspace_value, 'changed_files': [str(path) for path in changed_files], 'summary': str(summary), 'details': {'tests_generated': int(tests_generated), 'tests_passing': int(tests_passing)}, 'error': None}
except Exception as exc:
    result = {'status': 'failed', 'workspace_id': workspace_value, 'changed_files': [], 'summary': '', 'details': {}, 'error': str(exc)}
result