# Auto-generated by grail — this is what Monty actually executes

def add() -> int:
    """Add two numbers."""
    return a + b

def multiply() -> int:
    """Multiply two numbers."""
    return a * b