# Auto-generated by grail — do not edit

from typing import Any

test_file: str
target_file: str

async def run_pytest(path: str) -> dict[str, Any]:
    """Run pytest on a test file and return results."""
    ...
