# Auto-generated by grail — this is what Monty actually executes

_ = noop

async def _safe_list_dir(path: str) -> list[str]:
    try:
        return await list_dir(path=path)
    except Exception:
        return []
fixtures_dir = 'fixtures'
fixtures: list[dict[str, str]] = []
if await file_exists(path=fixtures_dir):
    entries = await _safe_list_dir(path=fixtures_dir)
    for name in sorted(entries):
        fixtures.append({'name': name, 'path': f'{fixtures_dir}/{name}'})
result = fixtures
result