# Auto-generated by grail — do not edit

noop: bool

async def list_dir(path: str = .) -> list[str]:
    """List file names in a directory."""
    ...

async def file_exists(path: str) -> bool:
    """Check if a file or directory exists."""
    ...
