# Auto-generated by grail — do not edit

fixtures: list[object]
format_input: str
node_text_input: str | None

async def read_file(path: str) -> str:
    """Read the text contents of a file."""
    ...

async def write_file(path: str, content: str) -> bool:
    """Write text content to a file."""
    ...

async def file_exists(path: str) -> bool:
    """Check if a file or directory exists."""
    ...
