# Auto-generated by grail — this is what Monty actually executes

from typing import Any
try:
    if not source_code:
        raise ValueError('Source code is required.')
    args = ['check', '--output-format', 'json', '--select', 'E,W,F']
    if not check_only:
        args.append('--fix')
    args.append(file_path)
    issues_raw = await run_ruff_check(path=file_path, fix=not check_only)
    if isinstance(issues_raw, dict) and 'error' in issues_raw:
        error_message = issues_raw.get('stderr', '').strip() or f"ruff exit code {issues_raw.get('exit_code')}"
        result = {'result': None, 'summary': f'Error: {error_message}', 'knowledge_delta': {}, 'outcome': 'error', 'error': error_message}
    else:
        issues = []
        if issues_raw:
            for issue_data in issues_raw:
                code_val = issue_data.get('code')
                if isinstance(code_val, dict):
                    code_str = str(code_val.get('value', ''))
                else:
                    code_str = str(code_val or '')
                fix_data = issue_data.get('fix')
                fixable = fix_data is not None
                if isinstance(fix_data, dict) and fix_data.get('applicability') == 'unfixable':
                    fixable = False
                issues.append({'code': code_str, 'line': issue_data.get('location', {}).get('row', 0), 'col': issue_data.get('location', {}).get('column', 0), 'message': str(issue_data.get('message', '')), 'fixable': fixable})
        fixable_count = sum((1 for issue in issues if issue.get('fixable')))
        total = len(issues)
        raw_result = {'issues': issues, 'total': total, 'fixable_count': fixable_count}
        if total == 0:
            summary = 'No lint errors found'
            outcome = 'success'
        elif fixable_count > 0:
            summary = f'Found {total} lint errors, {fixable_count} fixable'
            outcome = 'partial'
        else:
            summary = f'Found {total} lint errors'
            outcome = 'partial'
        result = {'result': raw_result, 'summary': summary, 'knowledge_delta': {'lint_errors_remaining': total, 'lint_errors_fixable': fixable_count}, 'outcome': outcome}
except Exception as exc:
    result = {'result': None, 'summary': f'Error: {exc}', 'knowledge_delta': {}, 'outcome': 'error', 'error': str(exc)}
result