# Auto-generated by grail — do not edit

from typing import Any

source_code: str
file_path: str
check_only: bool
issues_input: list[dict[str, Any]] | None
lint_report_json: str
stderr: str
exit_code: int
