# Auto-generated by grail — do not edit

from typing import Any

source_code: str
file_path: str
check_only: bool

async def run_ruff_check(path: str, fix: bool) -> dict[str, Any]:
    """Run ruff linter check on a file."""
    ...
